import json
import os
import re
import urllib.request

def main():
    print("Updating HaxBall Headless Engine...")
    try:
        # 1. Get cache hash
        with urllib.request.urlopen("https://www.haxball.com/cache_hash.json") as response:
            hash_data = json.loads(response.read().decode("utf-8"))
            cache_hash = hash_data.get("hash")
        
        if not cache_hash:
            raise ValueError("Could not find hash in cache_hash.json")
            
        print(f"Latest cache hash: {cache_hash}")
        
        # 2. Download headless-min.js
        url = f"https://www.haxball.com/{cache_hash}/__cache_static__/g/headless-min.js"
        print(f"Downloading from: {url}")
        with urllib.request.urlopen(url) as response:
            js_code = response.read().decode("utf-8")
            
        # 3. Apply Nodeify-like transformations to run in QuickJS / Node/Python environments
        # Replace window and document references where needed
        js_code = js_code.replace("typeof window", "typeof globalThis")
        js_code = js_code.replace("window.crypto", "globalThis.crypto")
        js_code = js_code.replace("window.WebSocket", "globalThis.WebSocket")
        js_code = js_code.replace("window.XMLHttpRequest", "globalThis.XMLHttpRequest")
        
        # 4. Save to headless_min.py
        target_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "engine")
        os.makedirs(target_dir, exist_ok=True)
        
        target_file = os.path.join(target_dir, "headless_min.py")
        with open(target_file, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by update_engine.py\n")
            f.write(f"HASH = {repr(cache_hash)}\n")
            f.write(f"HEADLESS_MIN_JS = {repr(js_code)}\n")
            
        print(f"Engine updated successfully and saved to {target_file}!")
    except Exception as e:
        print(f"Error updating engine: {e}")

if __name__ == "__main__":
    main()
